db:
  user: root
  password: 123456
  host: 127.0.0.1
  port: 3306
  name: demo
  charset: utf8mb4
  max_open_conns: 50
  max_idle_conns: 10
  conn_max_lifetime: 3600

log:
  file: app.log
  level: info
  max_size: 100
  max_age: 31
  max_backups: 31
  compress: true
